version: '3'
services:
  bot:
    image: fulviocoelho/jenkins-bot:latest
    container_name: bot
    ports:
      - 8080:8080
    environment:
      - CLANID={{bot_clan_id}}
      - COMMAND={{bot_calling_command}}
      - HEARTBEAT={{interval_in_seconds}}
      - ME={{author_id_from_used_account}}
      - TOKEN={{auth_token_for_discord}}
    deploy:
        resources:
            limits:
              cpus: '0.5'
              memory: 300MB